### ISSUE TITLE
toFixed() digits argument must be between 0 and 20

### ISSUE THREAD

**Issue by andrevenancio** [Jam3/react-f1#24]
I got this error a couple of times before:
`Uncaught RangeError: toFixed() digits argument must be between 0 and 20`;

I get it when I'm changing states using an ease normally. Don't know exactly why.

**Comment by ltbittner** [comment]
Getting the same error.

**Comment by andrevenancio** [comment]
@mikkoh I think this is related with `f1-dom`. any progress on how to avoid this? Happens when I use `traslate` with ease `quadInOut`.

**Comment by neo** [comment]
Getting the same error.
